### ISSUE TITLE
 how to setting wifi and bluetooth?

### ISSUE THREAD

**Issue by luuillu** [833M0L3/H96MaxX3#1]
thanks for your document,  I am successfully installed the armbian on my h96 box, every thing is ok ,but the wifi and blue tooth is not work,  do you know how to fix this problem? thank you.

**Comment by 833M0L3** [comment]
Unfortunately, I am not using Bluetooth and WiFi as they are not being used in my use case.  But I am pretty sure, Bluetooth and WiFi problem can be fixed by reading this thread discussion. https://forum.armbian.com/topic/13992-h96-max-x3-specifics-only/
