### ISSUE TITLE
Can you install a DE like xfce or lxde using this tutorial?

### ISSUE THREAD

**Issue by juanmarcosdev** [833M0L3/H96MaxX3#5]
I need to use my tx box as a mini pc, not as a server, so i need a DE. Can you follow these steps and in the terminal of armbian, install a DE? Or it only works just as a server.

Thanks for the help it is not an issue but i need help and advice from people that know this topic.

**Comment by 833M0L3** [comment]
@juanmarcosdev You can install DE easily. If you are familiar with Linux commands and their package manager based on distros, then it's a few commands away and easily installable. Look on youtube for how to install DE on a desktopless Linux machine.
