### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hapishyguy** [833M0L3/H96MaxX3#6]
I have a question. Whats your email or contact?

**Comment by 833M0L3** [comment]
Please drop question here

**Comment by hapishyguy** [comment]
ok. 
Is there any way to make make some kind of launcher tha connects to a server and then we can make changes to the launcher from the server(webpanel) and also to upload add and delete apps to the device/launcher from the server. 
How can we make such a thing?

**Comment by 833M0L3** [comment]
@hapishyguy , you could do that by installing a premade web software that you can host on the server. For example you can try this https://casaos.io/

**Comment by hapishyguy** [comment]
i forgot to mention that i need it for android. casaos might not be good for this purpose. anything else?

**Comment by 833M0L3** [comment]
@hapishyguy I have no idea of such a system that is available for free. You could build such system from the scratch if you have experience with native android app development, it's not that hard.
