### ISSUE TITLE
S905x3: all 4GB of RAM available?

### ISSUE THREAD

**Issue by gitisgreat2023** [833M0L3/H96MaxX3#7]
With other versions, of 4GB of RAM only about 3.5GB are available. Probably due to reserved RAM.

Is this also the case here? How much of the 4GB of RAM are available?

**Comment by 833M0L3** [comment]
Yes , you can see the screenshot of neofetch there

**Comment by gitisgreat2023** [comment]
Looked at it.... it's not... 3630MB available, where 4096MB expected, so also 466MB missing. Weird.
