### ISSUE TITLE
Not an issue but a big thank you! 💖 I successfuuly installed Armbian

### ISSUE THREAD

**Issue by petesimon** [833M0L3/H96MaxX3#8]
I have a X88 Pro X3 S905x3, 2GB/32GB TV box. It was neglected and unused for 3 years. But I found this github page one week ago,  researched Armbian and decided to dust-off the X88. After experimenting, I installed _Armbian_24.11.0_amlogic_s905x3-x88-pro-x3_jammy_6.1.112_server_2024.10.02_ , and used the data files _u-boot-x96maxplus.bin_ and _meson-sm1-x88-pro-x3.dtb_. I had to use 'xrandr' command to set the resolution to 1280x720/60 in Xorg. Gigabit ethernet and USB 3.0 and things work nicely but there is no sound or bluetooth. I guess some cheap USB BT and USB sound 'card' adapters would suffice. Thanks again friend! 😁

![Screenshot_2024-10-14_23-15-14](https://github.com/user-attachments/assets/d02b9d6a-0f43-45af-8825-cac677de1f3d)

![snapshot_ 2024-10-14_16 05 24 -OWL](https://github.com/user-attachments/assets/67289742-00a4-49c6-b218-39c33da6f6d0)

![X88ProX3-product](https://github.com/user-attachments/assets/5e7ffe59-4683-4ac9-aa95-bd65cf20bbd2)

**Comment by 833M0L3** [comment]
Good to know. But recommend using it as a server rather than a desktop experience. I can see a huge number of frame drops on your YouTube playback stats. The hardware acceleration for graphics is not supported on these boxes so the overall experience is not that great.

**Comment by petesimon** [comment]
@833M0L3 Thank you for your reply. I am glad you still check this page. Oh, I was fascinated by the nice animals and didn't pay any attention to the technical statistics in youtube. haha. Yes, I am using it primarily as a storage server. The up/download speeds are good. I only wanted to experiment shortly with the xfce4 desktop and some graphical programs. Here is a link to my armbianmonitor log https://paste.armbian.com/oxaheyesub . Cheers mate.

**Comment by petesimon** [comment]
@833M0L3 Thank you for your reply. I am glad you still check this page. Oh, I was fascinated by the nice animals and didn't pay any attention to the technical statistics in youtube. haha. I only wanted to experiment shortly with the xfce4 desktop and some graphical programs.  Yes, I am using it primarily as a storage server. The transfer speed of files is good.  Here is a link to my armbianmonitor log https://paste.armbian.com/oxaheyesub . Cheers mate.

**Comment by 833M0L3** [comment]
@petesimon Good to know that your old box came to use. I also recommend you to check out https://github.com/devmfc/debian-on-amlogic, it has more cleaner images and is very lightweight and optimized. I have been using those images for a while. Had issues with Ophub images as they were bloated with unnecessary drivers and tools.
